### ISSUE TITLE
debug LED blinks on I2C traffic (S8 Badge poweron)

### ISSUE THREAD

**Issue by chaseadam** [parallellogic-/SuperconAddOn2024#1]
S8 badge https://github.com/Hack-a-Day/2024-Supercon-8-Add-On-Badge/tree/main/hardware

my guess is it has something to do with the state of the non-power SAO header pins which is putting the device into a debug/programming mode indicated by a blinking Debug LED.

Attaching the SAO after S8 Badge poweron does not result in the same behavior.

This is very reproducible.

Is it possible to us the UART lines to reprogram the STM8?

**Comment by chaseadam** [comment]
It appears to start the screensaver, but then switches to blinking debug LED.

It occurs when GPIO pins are not connected as well (just power and I2C)

**Comment by chaseadam** [comment]
I suspect this comment indicating the app will stop when it receives a valid I2C packet is the culprit

https://github.com/parallellogic-/SuperconAddOn2024/blob/88335f758e7a8f4b2c9e10e32ae3f134e9ea2fbe/src/sao2024/main.c#L10

but after the main application it switches to "developer mode" which only activates the Debug LED once during setup

https://github.com/parallellogic-/SuperconAddOn2024/blob/88335f758e7a8f4b2c9e10e32ae3f134e9ea2fbe/src/sao2024/developer.c#L9

The only other area which I could think is causing the blink is in the API code:

https://github.com/parallellogic-/SuperconAddOn2024/blob/88335f758e7a8f4b2c9e10e32ae3f134e9ea2fbe/src/sao2024/api.c#L202C15-L202C41

The debug LED appears to be controlled by `set_debug()`

**Comment by chaseadam** [comment]
After exiting the main loop of the badge after startup with CTRL+C on the Micropython console, I noted the debug LED toggles when an I2C message is received (i.e. when I execute `which_bus_has_device_id(0x30, debug=True)`.

Looks like the main loop of the S8 badge is sending several I2C messages on startup. I let it run a bit longer and noticed it blinks for a few seconds and then happens to stop with the Debug LED solid on.

**Comment by chaseadam** [comment]
This appears to be working as expected, but would be nice to be able to "re-enter" the `run_application()` with the buttons.

**Comment by parallellogic-** [comment]
Ah!  I'm terribly sorry, I didn't see your message.  Apologies, yes, this is unfortunately the intended behavior.  I wanted the badge to be in the default application mode (screen savers + games) until it received any valid I2C command, in which case it would be immediately apparent to the operator it was responding immediately to (any and all) operator input.  However, the default badge behavior (I didn't learn about until arriving at the con) pings all the I2C devices on power-up, which puts this SAO into developer mode as you've noted.  If you configure the badge to skip over the 0x30 device address, this should bypass the offending action and allow the device to remain in application mode.  Alternatively, if you hold down the boot button on the badge during power-ON, it will hold the badge in reset, applying power to the SAOs without any I2C traffic, which also allows the SAO to remain in application mode too.

_Attaching the SAO after S8 Badge poweron does not result in the same behavior._
The badge only queries the I2C bus for SAO addresses on boot-up, which is the problem area

_Is it possible to us the UART lines to reprogram the STM8?_
I don't have any provisions for that, sorry (the UART was a feature I nixed as redundant once it became apparent the I2C bus was fast enough to flush full frames at 60+ Hz).  I programmed these using the SWIM+RESET pins and an [ST-LINK/V2](https://botland.store/programmers/14281-st-linkv2-in-circuit-debugger-programmer-for-stm8-and-stm32-5904422342432.html), though I fully expect a ST-Link should work just as well https://www.amazon.com/CANADUINO-Compatible-Circuit-Programmer-Debugger/dp/B07B2K6ZPK

_I noted the debug LED toggles when an I2C message is received_
That's precisely the intended behavior!  Trying to give the developer visual feedback during initial boot-up of the I2C bus with this SAO.  Note the I2C API on the main page for additional commands: https://github.com/parallellogic-/SuperconAddOn2024/tree/main

_This appears to be working as expected, but would be nice to be able to "re-enter" the run_application() with the buttons_
Thank you for your feedback.  I did expose the buttons over the I2C API too, so there'd be contention between reading the button state/events as an input for relay over I2C vs taking action based on button pushes.  For future reference, what would you think of an I2C command to revert an SAO like this back to application mode?  One implementation could have the badge query the state of the buttons and then send the appropriate I2C command to revert to application mode.
